spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/darkenwald_db?createDatabaseIfNotExist=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=root
spring.datasource.password=BraveWorld

spring.jpa.database-platform= org.hibernate.dialect.MySQL5Dialect

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
spring.session.timeout=900



