apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: keycloak-headers
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "http"
      X-Forwarded-Host: "keycloak.local"
      X-Forwarded-For: "10.42.0.1"
      X-Forwarded-Port: "80"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-keycloak-path
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /auth
  